# Generated by Django 5.0.1 on 2024-01-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=255)),
                ('profession_experience', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('name_of_vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.vacancy')),
            ],
        ),
    ]
